### ISSUE TITLE
[Feature Request] Semi managed mode

### ISSUE THREAD

**Issue by tlvu** [GhostWriters/DockSTARTer#1241]
# Feature request

**Is your feature request related to a problem? Please describe.**
I prefer to install `docker` and `docker-compose` and any other tools needed myself.

This will make DockSTARTer integrate better on server that already run other docker-compose jobs and it's also better for the security (I like to know what exactly is installed on my own system).

**Describe the solution you'd like**
Just generate the `.env` and `docker-compose.yml` and let me run `docker-compose up -d` myself.

Following the "Alternate install (any system)" section on https://github.com/GhostWriters/DockSTARTer still end up with `sudo bash /home/"${USER}"/.docker/main.sh -vi` which still install new stuff.

Can DockSTARTer run simply without the install step and directly from the checkout dir?

**Comment by angrycuban13** [comment]
All that script does is install dependancies needed for DS. What new stuff are you referring to?

**Comment by tlvu** [comment]
I meant new stuff is the stuff it installs (new for the user running it).

**Comment by nemchik** [comment]
Sorry for not replying to this sooner.

Here are the steps you can use to accomplish what you want:

- Install docker >= `19.03.0` and compose >= `1.27.0` (DS requires versions equal or greater for both of these dependencies)
- Perform the alternate install from the homepage (DS will not reinstall or upgrade docker or compose if they are above the minimum versions)
- When you run DS via the menu, at the end you will be asked if you want to run compose, if you choose no it will still generate the `.env` and `docker-compose.yml` files and you can run them yourself whenever you like

Things to be aware of:

- If you edit your `.env` file and later run DS, the file will be reordered so that the global and vpn settings match https://github.com/GhostWriters/DockSTARTer/blob/master/compose/.env.example and all other variables are sorted alphabetically at the bottom
- If you edit the `docker-compose.yml` file and later run DS, the entire file will be erased and recreated. The intention is for you to put your modifications in a separate file named `docker-compose.override.yml` documented here https://dockstarter.com/overrides/introduction/

Please let me know if you have any other questions
