### ISSUE TITLE
Permission Error When Attempting to Install Applications.

### ISSUE THREAD

**Issue by tuanma123** [GhostWriters/DockSTARTer#126]
**Describe the bug**
Error in starting the containers installed by DockSTARTER. The final step of the app installation process always fails for me. In the particular I get following error:
ERROR: for radarr  Cannot start service radarr: error while creating mount source path '/home/username/.docker/config/radarr': mkdir /home/username/.docker/config: permission denied. The same error goes for all the containers I tried to install. I installed this on a new Ubuntu 18.04 server. I also attempted to give all permissions to the .docker but that did not seem to solve the issue. I used all the default values for the installation expect the media library location.

**To Reproduce**
1. Install DockerSTARTer.
2. Attempt to install applications.
3. See error

**Expected behavior**
Hopefully no error.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.1 (fresh install)

**Additional context**

**Comment by nemchik** [comment]
can you run `mkdir /home/username/.docker/config` (replace username)? that should work, having nothing to do with DockSTARTer.

**Comment by thewinger** [comment]
I have the same problem.

Also Ubuntu server 18.04, left everything default except media folders and when trying to start the contaiers I have the same "permission denied" issue.

Also, if I go into the .env file, the media folders are not the ones I wrote but the default ones.

**Comment by nemchik** [comment]
The screenshot helps a little, thank you! It looks like DS is making it through everything it's supposed to but docker compose is having trouble. I've got some ideas about how to fix it.

When you selected the DOCKERCONFIG folder, did you use `~/.docker/config` or did you use `/home/win/.docker/config`? I think there might be an issue with the way DS handles `~/`

Also did you allow DS to set the folder permissions on each folder?

I've got a potential fix, but what I have so far might just be one piece of the puzzle.

**Comment by thewinger** [comment]
Tried selecting /home/win/.docker/config and same output.

**Comment by thewinger** [comment]
To add, my configuration is as follows

Host: Windows 10 Education
Virtualbox 5.2.18 r124319
Guest: Ubuntu Server 18.04 LTS

Folders /mnt/xxx are Windows Shared Folders that I have mounted through VB's GUI and manual mount when it failed. Both of them with the same outcome.

Previously I tried following https://www.smarthomebeginner.com/docker-home-media-server-2018-basic/ tutorial and everything installed and worked as expected until I tried to add a TV Show to Sonarr that it said "Folder is not writable by user abc". And then is where I tried DockSTARTer.

**Comment by nemchik** [comment]
Would you be willing to test this out?

```
cd ~/.docker
sudo bash ~/.docker/main.sh -u
git checkout compose-user
```
Then run DockSTARTer with `sudo bash ~/.docker/main.sh`

That will put you on a test branch with a change I think might resolve the issue. To get back to stable you'll run this:
```
cd ~/.docker
git checkout master
sudo bash ~/.docker/main.sh -u
```

I think that will fix the issue of the app config folders not being created properly, but i'm not sure about the media folders yet. My first guess on that is you might need to do something like `sudo chown -R /mnt/movies` and do that for each folder (probably should NOT do it on the `/mnt` parent folder though).

**Comment by thewinger** [comment]
Followed what you said, same result.

**Comment by nemchik** [comment]
A quick google of this error https://www.google.com/search?q=docker+compose+ERROR%3A+for+Cannot+start+service+error+while+creating+mount+source+path+mkdir+permission+denied seems to point to this being a permissions issue and is really only present on systems involving docker on windows. Most of the responses are just to give permissions to the user running docker (in your case DS) but one response did mention trying to create each of the folders mentioned in the error manually from within the ubuntu vm and then seeing if everything runs ok. It's not ideal, but if you could give it a shot i'd be curious if it'll work. Specifically if you create those files I wonder if your containers will function properly (if they have the correct write access).

**Comment by thewinger** [comment]
Tried setting folders in /home/win/tv, /home/win/movies, etc. instead of the Shared folders and now the errors only happen in /home/win/.docker… folders.

ERROR: for sonarr  Cannot start service sonarr: error while creating mount source path '/home/win/.docker/shared': mkdir /home/win/.docker/shared: permission denied

ERROR: for radarr  Cannot start service radarr: error while creating mount source path '/home/win/.docker/shared': mkdir /home/win/.docker/shared: permission denied

ERROR: for transmissionvpn  Cannot start service transmissionvpn: error while creating mount source path '/home/win/.docker/shared': mkdir /home/win/.docker/shared: permission denied

**Comment by nemchik** [comment]
can you create that folder manually? (looks like just the shared folder at this point)

**Comment by thewinger** [comment]
I can create the .docker/shared folder but then the gives the error with each of the app folders inside config

**Comment by nemchik** [comment]
Ok. Every error it gives you about a folder you'll need to create that folder. Once we get past the folder errors let me know if there are any other errors. If there are none then I'm curious if it's able to actually let your apps function (like if the apps can write to the folders and save their configs).

I'm not sure at this point how to fix the issue about the folders because that seems to have something to do with permissions and I'm not well versed in the way you're running Ubuntu 😦

**Comment by tuanma123** [comment]
When I got those errors I tried both creating my folders manually and adding permissions to DockerStart but I still got the same errors. I tried running the commands you suggested, but I was getting a similar error as thewinger. I was running it on a fresh install of Ubuntu 18.04. I am going to try another fresh install of Ubuntu to see if that makes any difference.

**Comment by thewinger** [comment]
Created the app folders manually and containers went up.
I can enter Sonarr via http://myip.com:port/ but if I try to add a TVShow, it doesn't let me choose the folder /home/win/tv as stated in .env and if I choose /tv the it says **Folder is not writable by user abc** as it did when I followed smarthomebeginner docker guide.

**Comment by nemchik** [comment]
`/tv` is what you want in Sonarr, but the permissions would be the only thing i can think that might be keeping it from working. Can you run `ls -lah /home/win/tv` and then it should show you the user and group that owns the files there (usually the group name matches the username in most cases, if not please let me know, that's important!). From there run `id -u THE_NAME_THAT_OWNS_THE_FILES` and then tell me if the number it gives you is the same number you see in `~/.docker/compose/.env` for `PUID` and `PGID`?

**Comment by thewinger** [comment]
Started from scratch.
Had to mkdir the folders (config, shared and the ones from the apps) manually.
And now it doesn't give me the **Folder is not writable by user abc** error.

/home/win/tv folder has same username and group name and the id corresponds with the one in .env

Seen that it seem working I tried adding the shared folders again, but it goes back to the read-only file system error.

**Comment by nemchik** [comment]
To be honest from here I'm not sure what the issue is, but it's not specific to DockSTARTer. This issue might be something that we can have DS fix in the future for you, but I'm not sure why it's even happening so we have to find a fix first. The problem seems to be with permissions and docker compose. There might be some people in the LSIO discord (they made the containers) who could help if you mention permission issues with Sonarr https://discord.gg/YWrKVTn

**Comment by thewinger** [comment]
Thank you for your help and time.
I will ask there :)

**Comment by nemchik** [comment]
I've tagged this issue:
- invalid: this isn't an issue with DockSTARTer
- question: we need more info about what fixes this issue so we can determine if it's something DockSTARTer could account for in some way, or at least we can document the fix for others to find
- help wanted: I can't reproduce this, so I'll need people having this issue to help out so a solution can be found

**Comment by mattgphoto** [comment]
For the record, cannot reproduce on Ubuntu 18.04.1 myself. Done a few installs today.

**Comment by tcare** [comment]
I ran into this today on a fresh install of 18.04 running under Hyper-V. I recreated the VM without selecting docker in Ubuntu setup, and then installed the Hyper-V integration (apt-get install linux-virtual linux-virtual-tools) and it worked fine after that.

**Comment by jtoelen** [comment]
I had the same problem with a clean install ubuntu 18.04.
I discovered that there was already a docker installation present, but it was installed with Snap. DS used this docker/docker-compose resulting in permission errors.
After a snap remove of that docker, everything worked fine.

**Comment by nemchik** [comment]
@jtoelen that if something DS can handle, would you open a new issue about it so that it doesn't get lost and I'll make the changes required.
