### ISSUE TITLE
[Application Request] Replace LSIO ruTorrent image

### ISSUE THREAD

**Issue by triqster1** [GhostWriters/DockSTARTer#1264]
# Name of the application
rTorrent with ruTorrent

## GitHub
https://github.com/crazy-max/docker-rtorrent-rutorrent
or some other, but this seems to be the most well maintained one.

## Docker Hub/GitHub Registry
Docker Hub 	crazymax/rtorrent-rutorrent
GitHub Container Registry 	ghcr.io/crazy-max/rtorrent-rutorrent

### Additional context
LSIO ruTorrent image has been buggy and unmaintained for years. At long last they admitted it and the image is being deprecated. The above mentioned image is actively maintained. Basic things like theme support, IP flags are working and opening the csgi port even though it's using the socket.

I know there's the rutorrentVPN image, but this seems bloated for people who don't need VPN (eg on a seedbox) and has some of the same issues. The dated rtorrent version comes with it's own share of issues that have been fixed in more recent versions of rtorrent.

**Comment by angrycuban13** [comment]
> At long last they admitted it and the image is being deprecated. 

Can you please provide a source for this statement?

**Comment by nemchik** [comment]
Ref: https://github.com/linuxserver/docker-rutorrent/issues/188

I'd like to point out https://github.com/linuxserver/docker-rutorrent/issues/135#issuecomment-771094903 as well, kind of just to publicly call out that the way @triqster1 is going about discussing this publicly is coming across as quite pushy and outright rude.

Anyway with respect to changing the image DS uses, I'm not opposed to this. The LSIO image is NOT deprecated, but the current person designated as the maintainer has no interest in continuing to maintain it, thus the ask for a new maintainer to step up. 

crazy-max is a solid dude and his work is absolutely worth looking at as an alternative. hotio is as well. I will bring this up internally with the DS staff and we can come to an agreement about how to proceed with this, since it could potentially affect other images as well.

**Comment by triqster1** [comment]
I meant to link that issue but forgot, sorry.

And yes it was definitely rude of me and I did cross the line and it's totally fine to point that out. However they finally acknowledged this unmaintained image as such instead of continuing to ignore it.

Anyways, I agree, those are great alternatives. And a well maintained alternative that doesn't generate issues over basic broken features is usually the better option in my opinion. Thanks for the response, I'm glad to hear you're considering it.

**Comment by angrycuban13** [comment]
I don't have a lot of time in my hands these days so please feel free to create a PR
