### ISSUE TITLE
NFS auto mount

### ISSUE THREAD

**Issue by lurcheous** [GhostWriters/DockSTARTer#1278]
# Feature request

**I don't use any form of SMB on my network due to security, and getting dockstarter to work with smb shares is frustrating

**Describe the solution you'd like**
I have like a lot a dedicated NAS box with my files storage on

\\IP\mnt\zfs pool

can we set DockSTARTer to auto create a default mount smb and or NFS to \mnt  that auto connects to the physical hosts \mnt

**Describe alternatives you've considered**
going back to pre docker and manual maintaining as its less grief as there is a lot of assumption of knowledge, I know linux enough to maintain servers for work vps and metal. but never used docker as always found a pain to keep replicating shares and config on dozens of images rather than a single global config

**Comment by nemchik** [comment]
DockSTARTer's purpose is to run applications in containers. Setting up or managing storage is outside that scope.

The recommendation is that you setup your storage however you'd like, ex: use systemd or fstab or whatever you'd like to auto mount your nfs, smb, local disks, or even cloud storage to whatever mount point you'd like (usually under `/mnt`) and then with the `~/.docker/compose/.env` variable `DOCKERSTORAGEDIR` you would set the parent directory of all your storage mount (such as `/mnt`) and then all of the containers run by DS would be able to see and access all of that storage by looking for the `/storage` volume inside the containers.

So if you run Plex, and you have 3 NAS (one for movies, tv, and music) and you mount the following:
```
/mnt
/mnt/movies <- nas 1, NFS
/mnt/music <- nas 2, SMB
/mnt/tv <- nas 3, SMB
```
(you can use the same type of network protocol for all of them, I'm just illustrating above that you might have some NFS and some SMB)
You can then tell Plex to add your libraries by looking in `/storage/movies` and `/storage/music` and `/storage/tv`.

DS is specifically here to help you run docker containers (that contain applications). In a sense it is similar to using a package manager like `apt`. Running applications in docker (whether with DS or not) has many benefits. The primary examples I give are that you don't have to worry about dependencies like mono or python, especially when two applications depend on different versions of those dependencies conflicting. Also once you get everything running, if you need to move those applications to another system (maybe you want to split them up, or migrate everything to a new system entirely) you can simply move your config folder along with the files used to run your containers, and then run a command to fire up all the containers, and they will start up as if nothing happened. The applications have no idea they were moved. In the case of DS the docker specific files are all in `~/.docker` and the config is all in `~/.config/appdata`.

The learning curve with docker is not a tall mountain to climb. DS tries to make it even less of a large task to undertake. Once you have that down, using docker will hopefully seem like the natural choice for running anything you possibly can, in part because it brings consistency to how things are run across any distro (Ubuntu, Fedora, etc). There are even command line utilities like `jq` that can be run via docker, rather than installing them locally. There are advantages and disadvantages to using docker, don't get me wrong, it's not all superior to everything, but at the moment it's a very good (in my subjective opinion) option for many things.

I hope DS can be helpful to you, and please feel free to stop by our Discord chat server and ask for any help you might need (including help with getting your storage needs setup prior to working with DS). https://dockstarter.com/discord
