### ISSUE TITLE
[BUG] Setting permissions for..... may be unsafe

### ISSUE THREAD

**Issue by musklor** [GhostWriters/DockSTARTer#1299]
# Bug report

**Describe the bug**

Setting permissions for /srv/dev-dis
k-by-uuid-xxxxxx/appdata/.compose.bac
kups outside of /srv/dev-disk-by-uuid-xxxx/homedir/xxxx may be unsafe.

**To Reproduce**
OMV, appdata configured with DS GUI.
I launch DS -u and I have two warns.

**Expected behavior**

**Screenshots**

**System**
RPI4/OMV/Docker

**Additional context**

**Comment by angrycuban13** [comment]
This isn't necessarily a DS issue but it might be OMV. 

We don't recommend using OMV with DS as we can only provide very limited support for it.

**Comment by musklor** [comment]
You're alright.
Thanks

**Comment by nemchik** [comment]
This is just a warning and won't stop you from being able to use DS. In the future I may add some kind of "are you sure" prompt https://github.com/GhostWriters/DockSTARTer/blob/355240f85393fd7676d006b3427a25adb217974b/.scripts/set_permissions.sh#L22 but again it would not stop you, just confirm that you do in fact mean to be using the path entered, since it's outside of your home directory. Ideally you should be careful about setting permissions on any folder outside your home directory.
