### ISSUE TITLE
[BUG] ds -c no longer recreating containers when new versions are available

### ISSUE THREAD

**Issue by mturley** [GhostWriters/DockSTARTer#1316]
# Bug report

**Describe the bug**
I can't seem to get docker-compose (via `ds -c`) to update my containers to newer versions.

**To Reproduce**
1. Confirm that there is a newer version available for some container. For example, in the Plex UI I saw an alert saying an update was available, and I confirmed that the version on docker hub was newer than what I was running.
2. Run `ds -c`. See all containers listed as `up-to-date`.

**Expected behavior**
Previously, any containers with newer versions available would be recreated. That seems to have stopped happening entirely for me for a long while. Not sure if it was because of a DockSTARTer update or something else.

**System**

- OS: Debian
- Version: 10 (buster)

**Additional context**

After reproducing the issue I tried fully upgrading all dependencies (`apt update && apt upgrade`) and updating DockSTARTer to the latest master, then rebooting. `ds -c` still didn't update my containers. I had to manually run a `docker-compose up --force-recreate` which did in fact pull the newer versions for me.

**Comment by nemchik** [comment]
This is actually not a bug. `docker-compose up` (shortcut `ds -c`) is just telling docker to run the containers with the versions of the images you have downloaded. If you don't have anything downloaded then it downloads images for the first time. To get updates you would need to pull new images with `ds -c pull` and then recreate the containers with the new images with `ds -c`

**Comment by mturley** [comment]
That's strange, because for the last 2 years of my `ds` usage, I could just run `ds -c` to get updates. Maybe something was wrong before?

**Comment by mturley** [comment]
Maybe I should just open a feature request to add an "update containers" action in the ncurses UI :)

**Comment by nemchik** [comment]
I can only imagine that you may have had watchtower or ouroboros running. Those would update your containers automatically, but compose would not be aware of those updates. When you would run compose (via `ds -c`) it would recreate your containers with the most recent image that your system has available without pulling new images. Since watchtower and ouroboros had already pulled updated images you would see compose recreating your containers. The updates would have already been applied and running by ouroboros or watchtower though, so if you check the version of the application before and after running `ds -c` you would likely see the same version.

All that being said, having an option in the menu to update on demand is not a bad idea.

**Comment by mturley** [comment]
Ah that makes sense. Thanks for the explanation, sorry for my limited familiarity with docker!
