### ISSUE TITLE
[Application Request] Pi-Hole & Unbound (cbcrowe/pihole-unbound)

### ISSUE THREAD

**Issue by samAheenan** [GhostWriters/DockSTARTer#1495]
# Name of the application
pihole-unbound

## GitHub
https://github.com/chriscrowe/docker-pihole-unbound

## Docker Hub/GitHub Registry
https://hub.docker.com/r/cbcrowe/pihole-unbound

### Additional context
As per [the request](https://github.com/chriscrowe/docker-pihole-unbound/issues/138) on the container maintainer's page, I think this would be an excellent addition to the DockSTARTer suite!

**Comment by shahvirb** [comment]
@samAheenan I can't promise I'll get to this but in the meantime you should know that you can still run their docker container through the `docker-compose.override.yml file.`

Read more here: https://dockstarter.com/overrides/introduction/
Specifically pay attention to the "Add a New App" heading on that page.

For example you can copy some of the contents of https://github.com/chriscrowe/docker-pihole-unbound/blob/main/one-container/docker-compose.yaml into your dockstarter `docker-compose.override.yml` file, then review and update all the environment variables as per your .env file and then when you run `ds -c` you should see this new container created.

**Comment by nemchik** [comment]
This is interesting. We do have pihole in DS already, so I wonder if it makes sense to separately include a container for unbound. The thing would be configuring them together wouldn't be automatic unless we use the single container option from this repo as its own standalone container (meant to be used instead of the default pihole container).

I lean towards having a separate unbound container and documenting using the container mentioned above as an override by just replacing the pihole image with the single container image above and adding anything unbound needs.

**Comment by samAheenan** [comment]
Thanks to you both for your responses. 

My thought process for requesting this container was along the lines of how there are Deluge / DelugeVPN and Transmission / TransmissionVPN containers. The single container option from the repo was what I had in mind as it would appear to simplify configuration but I am totally on board with whatever you guys decide is best.

**Comment by samAheenan** [comment]
It looks like there could be some interest in this from [this Reddit thread.](https://www.reddit.com/r/pihole/comments/x5qpvu/running_unbound_within_pihole_docker_container/)
