### ISSUE TITLE
[BUG] Duplicati not starting

### ISSUE THREAD

**Issue by daveb92** [GhostWriters/DockSTARTer#1815]
# Bug report
Clean install of Duplicati, container does not start up instead error message is: 

***      Missing encryption key, unable to encrypt your settings database     ***
*** Please set a value for SETTINGS_ENCRYPTION_KEY and recreate the container ***

This is found on the upstream container: https://github.com/linuxserver/docker-duplicati/issues/81

Need to add in to app variables for this container an environmental variable for "SETTINGS_ENCRYPTION_KEY="

**Comment by meminens** [comment]
I am having the same issue. What's the recommended fix/workaround?

**Comment by angrycuban13** [comment]
Since the issue has been identified upstream, there's nothing that DockSTARTer can do until it is fixed. The only option here is to use an [override ](https://dockstarter.com/overrides/introduction/) and 

1. Pinning Duplicating to a previous version where the issue was not present or 
2. Find another image from a different maintainer and use it
