### ISSUE TITLE
[watcher] Posters are not in the config directory

### ISSUE THREAD

**Issue by UnR34L** [GhostWriters/DockSTARTer#212]
It looks like posters are being saved in '/app/watcher/userdata/posters/' inside the container, makes it difficult to backup.

If you don't have them and restore the config folders, you end up with a broken website.

**Comment by nemchik** [comment]
I'm actually very surprised by this since it's an LSIO container. We can resolve this with another volume, but it's not documented at all on the container and I'm surprised the container doesn't just have the userdata folder pointed to `/config`. There seems to have already been an issue for this opened on the git repo for the image https://github.com/linuxserver/docker-watcher/issues/1 but it was closed with no actual resolution. I will comment on it asking that it be reopened and resolved at the container level either by putting the userdata folder in `/config` or at least by documenting the need to mount another volume in the readme.

**Comment by nemchik** [comment]
Also FYI the watcher container readme seems to indicate that it is not considered fully tested and ready for use.

**Comment by nemchik** [comment]
Seems the dev of watcher has documented that specific folder here https://github.com/nosmokingbandit/Watcher3/wiki/Docker-Compose-Example I may be able to make that adjustment and have it work decent with DS, but I'm also inclined to completely remove this watcher container from DS as it is unreleased/unsupported by LSIO at this time. The dev of Watcher does not seem to be actively pursuing a method for anyone to use Watcher in Docker aside from referencing the unreleased LSIO image.

**Comment by UnR34L** [comment]
Watcher looks promising, it's pretty temperamental when it comes to updates but overall I've had a better experience than I've had with couchpotato or radarr.

Wouldn't something like this work, at least for now ?

> services:
>   watcher:
>     image:           linuxserver/watcher
>     container_name:  watcher
>     restart:         always
>     environment:
>       - PGID=${PGID}
>       - PUID=${PUID}
>       - TZ=${TZ}
>     volumes:
>       - /etc/localtime:/etc/localtime:ro
>       - ${DOCKERCONFDIR}/watcher/config:/config
>       - ${DOCKERCONFDIR}/watcher/userdata:/app/watcher/userdata
>       - ${DOCKERSHAREDDIR}:/shared
>       - ${DOWNLOADSDIR}:/data
>       - ${DOWNLOADSDIR}:/downloads
>       - ${MEDIADIR_MOVIES}:/movies

**Comment by nemchik** [comment]
That should do it. I'm going to sleep on it and decide how to proceed. I hate the idea of backpedaling and removing watcher from DS. On the other hand DS should not be adding apps in this state where the dev does not have an active interest in maintaining their own Docker image, or willing to work with a reputable maintainer like LSIO.

Since the image is not considered publicly released or maintained and the dev of watcher isn't making their own image I'm debating removing it from DS.

**Comment by nemchik** [comment]
I have opted to remove watcher from DS but provide an override so that you may run watcher with DS.

https://gist.github.com/nemchik/4bb6f5ea14571e4b623ad70af324d69f

There are other ways to run watcher without DS if you choose.

If in the future watcher has an officially released and supported docker image (by LSIO or otherwise) I will review it and reconsider it for inclusion in DS.
