### ISSUE TITLE
traefik

### ISSUE THREAD

**Issue by JuezFenix** [GhostWriters/DockSTARTer#236]
traefik: 

Info about it: 

https://traefik.io/

Docker and integration:

Traefik have a official docker container, they only need one file (config), a bind to docker socket and 2 ports. Traefik is completely dynamic and only need a few tags on the containers to know all the details about wath to do (example: port, protocol and subfolder).

Reason 

Can be used to transforms a tons of ports to a hierarchy of subdomains or folders. As well can be used to use the same credentials to all services and protect that not support it (like h5ai). In addition, another thing that can be done is to use the same certificate for the entire environment (requested on traefik first run using the acme integration).

**Comment by nemchik** [comment]
Thanks for submitting these separate. I will say I'm hesitant with traefik because to my knowledge it requires additional modifications to the yml (labels) to work. I may be wrong and you might be able to configure it without yml labels.

Also we have LSIO letsencrypt which does the same thing. I'm not opposed to having two apps that do the same thing, just commenting that DS does have a reverse proxy option for those wanting it.

**Comment by robertbaker** [comment]
The benefit of traefik is you less setup for reverse proxying. No more going into proxy-confs and enabling the config. It only requires labels if the docker container isn't named or you want a different name than the container for the subdomain.

It also natively supports letsencrypt, so there's no need to edit the env with subdomains.

I'm anxiously awaiting this.

**Comment by robertbaker** [comment]
@nemchik Is this something I can help contribute? If I add the ymls in .apps what else do I need to do?

**Comment by nemchik** [comment]
You're more than welcome to contribute. Have a look at the merged PRs that add other apps to see how they look. Generally yes you're just adding the yml files, adding a few variables in the `.env` file, and adding a section to the menu `sh` file so that the app has a description in the menu.

**Comment by robertbaker** [comment]
@nemchik I'm working on it now.
How do you feel about appname.labels.yml?

**Comment by nemchik** [comment]
I've been trying to avoid APPNAME.labels.yml but I think it's the only way DS can add Traefik. We'll need another env var for each app then as well to control if an app should have the labels merged.

**Comment by robertbaker** [comment]
Does it really matter if the labels are there even if traefik isn't used?
It's just meta data.

**Comment by nemchik** [comment]
It might have no effect on the end user, but then it's just adding useless clutter and can lead to confusion when troubleshooting.

The network stuff shouldn't be needed as long as traefik is on the same bridge network as the other apps (DS already does this the network is called `compose_default`).

I've been told traefik can operate without the labels, but I don't know how true that is.

**Comment by robertbaker** [comment]
It should be possible without any labels,  I took the time to do labels
just in case. I should be able to test this soon and I'll do so without the
labels. My understanding is that they are only needed if you want to
override the convention defaults.

If the labels are needed, then it might make more sense to use
appname.traefik.yml, in case other apps in the future use docker labels.

The network stuff isn't needed, but it's useful for when you want to
isolate containers to prevent them from accessing the internet or restrict
something to only one network, like VPN. I'll leave that up to you, I think
it makes things a bit less ambiguous, if not more secure.

Another thing that would be nice is using depends_on, but I'm not sure if
that's really needed.

However, besides providing a sample override with them, I don't think it
can be added to the ymls b/c it will fail if it doesn't exist.

**Comment by nemchik** [comment]
You're right about depends_on. Let's avoid that for now.

Networks the way you describe can provide more security, but for it to mean anything in DS the user would have to use overrides anyway. We're either including everything on the proxy network (because we don't know what they may or may not proxy) or we're making an env var to let the user tell us what gets proxied.

I'd prefer if traefik is added that it's in a way that's minimally invasive to other apps. The networks and labels are a bit of a shake up. If it can be done without them I'd love to have that work. If not then we'll continue discussing the best way to keep it flexible and simple for everyone.

**Comment by nemchik** [comment]
I am closing this along with #272 
Please see my response and reason commented in the PR.
