### ISSUE TITLE
Mailu - Postfix

### ISSUE THREAD

**Issue by DArkes1312** [GhostWriters/DockSTARTer#273]
Looking for a good SMTP / postfix docker with web interface ; I found this one:

https://mailu.io/

DOCKER: https://hub.docker.com/r/mailu/postfix/

It look good enough, perhaps we could have it added ? ♥

**Comment by nemchik** [comment]
I notice mailu has many images aside from postfix. Just curious, what do the others do?

**Comment by DArkes1312** [comment]
As example ; https://hub.docker.com/r/mailu/admin/ this one is the web interface they're providing since SMTP usually don't have anything like this.

Basically a bunch of options they're providing.

https://hub.docker.com/r/mailu/setup/

Should be the one in use I believe !

**Comment by sixshooterz** [comment]
I don't know if this is appropriate but I'd like to voice my support and request for mailu to be added to DockSTARTer.  As someone who's **very** wet behind the ears with Docker in general, being able to add a fully functioning and fully featured mailserver would be amazing.  I came on here to ask how I'd go about adding something like that to my docker-compose file and .env files because it's just a bit much for me to figure out.

Thanks!

**Comment by nemchik** [comment]
I should have time to get mailu in this month, but I'm still a bit unclear as to which image we should be using and why there are so many images for this app.

**Comment by sixshooterz** [comment]
It’s a collection of images. Instead of having all services in one image,
they’ve broken each piece out to a separate docker image. You don’t have to
have each one but some of us will want all of the components to have a
full-fledged mailserver complete with webmail.

**Comment by nemchik** [comment]
This is a bit of a complex idea. I'm willing to discuss it but I'm going to say up front that if it's too complicated that may be a little out of scope for this project. In that scenario we may look into providing example overrides on the wiki so that others can easily setup mailu.

Back to business, assuming we continue with the intention of including mailu, what containers are the minimum to make it work?

**Comment by sixshooterz** [comment]
I would counter that, up front, that this is likely a niche request and one
that may not be worthwhile sinking a lot of time into and a Wiki page would
likely more than suffice.

They have their own docker-compose.yml and .env files listed here:
https://mailu.io/compose/setup.html

Would it be as simple as copying the compose and pasting at the end of an
existing override.yml? And the .env file and pasting at the end of our
current one?  Is there a way, when it merges changes during an update or ds
-c run, to keep formatting with comments and such? I think right now it
only keeps the actual settings (can’t confirm 100% without checking mine,
and I’m not at the computer). I’m one for copious comments to keep things
organized!

If it’s as simple as merging the two files and editing the necessary
sections per Mailu’s documentation I may have let the newness overwhelm me
without rationalizing things first.
