### ISSUE TITLE
Migrate from bind to volumes

### ISSUE THREAD

**Issue by robertbaker** [GhostWriters/DockSTARTer#289]
**Is your feature request related to a problem? Please describe.**
Volumes are the preferred mechanism for persisting data generated by and used by Docker containers. While bind mounts are dependent on the directory structure of the host machine, volumes are completely managed by Docker. Volumes have several advantages over bind mounts:

Volumes are easier to back up or migrate than bind mounts.
You can manage volumes using Docker CLI commands or the Docker API.
Volumes work on both Linux and Windows containers.
Volumes can be more safely shared among multiple containers.
Volume drivers let you store volumes on remote hosts or cloud providers, to encrypt the contents of volumes, or to add other functionality.
New volumes can have their content pre-populated by a container.
Windows Support

**Describe the solution you'd like**
https://docs.docker.com/storage/volumes/

**Describe alternatives you've considered**
None

**Comment by nemchik** [comment]
So to be clear I think we have some terminology mixed up.

DockSTARTer does not use mounts or bind mounts. It uses volumes. It does not however use named volumes.

Reference https://docs.docker.com/compose/compose-file/#volumes since we're using compose.

https://github.com/GhostWriters/DockSTARTer/issues/225 I commented that there would be little benefit to DockSTARTer using named volumes, but specifically it's because we're using `.env` to define where volumes go. Switching to named volumes would mean that volumes would remain persistent even when an app does not use them, unless you prune your system (which DS includes an option to do), but all that means is there's leftovers after stopping at so e if you as the end user don't remember to clean house. Your data on your disk remains in tact regardless whether it's defined as a named volume in docker.

**Comment by nemchik** [comment]
P.s. as you can see by the date on the other issue, it wasn't too long ago that I looked into this myself, and it's because I didn't know much about the topic before looking into it. I'm still not an expert by any means, but the way I understand it is as described above. If I'm wrong about something I'm more than happy to discuss it! I really appreciate you looking into things like this, you're learning more than most do about how docker works. I don't mind discussing why things are setup certain ways in DockSTARTer, or changing things that can be made better.
