### ISSUE TITLE
Creating network

### ISSUE THREAD

**Issue by b0red** [GhostWriters/DockSTARTer#307]
**Describe the bug**

**To Reproduce**
When I try to install any app from "sudo ds", like couchpotato, I keep getting the following error:
```
Creating network "compose_default" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
2018-10-08 17:09:10 [FATAL]      Docker Compose failed.
```

**Expected behavior**
I expect that the app would install in the container and the container would start.

**Screenshots**

**System (please complete the following information):**
 - OS: Ubuntu 18.04 headless

**Additional context**
Only running the portainer container, standalone, i e; I've installed it outside the DockSTARTer app. This is running fine with the following output from **docker network ls**;
```
NETWORK ID          NAME                DRIVER              SCOPE                                                                     
cd2e32180aab        bridge                bridge               local 
beefb6044910        host                    host                  local
434204b7f8c6        none                   null                   local
```

**Comment by nemchik** [comment]
It looks like somehow you've already got a docker bridge network using the only available IP your host has.
DockSTARTer is trying to create a network for you. Would you be able to try removing the existing docker networks you have and then run `sudo ds -g` to see if DockSTARTer recreates the right ones for you?

You will likely need to join your existing Portainer to the network DockSTARTer creates rather than directly to the `bridge` network.
