### ISSUE TITLE
Running on Arch Linux?

### ISSUE THREAD

**Issue by faurehu** [GhostWriters/DockSTARTer#311]
I plan on running my HTPC on my Arch Linux system and, sadly, this distro is not covered in the setup instructions.

I noticed I need either newt or whiptail and I cannot find them on the AUR listings.

I would also appreciate a way of setting this up without running a script from the internet. I'm OK with running a docker container but not too sure about running commands on my own host.

**Comment by nemchik** [comment]
DockSTARTer relies on the https://get.docker.com/ script to install the latest version of docker. That script does not indicate support for Arch Linux. Due to this, I do not believe the "Install Dependencies" option in DockSTARTer will work on Arch Linux. If there is another way to install the latest version of Docker (that matches the version available in the official docker script) then DockSTARTer could add support for Arch Linux.

Newt is a package for CentOS and Fedora that includes whiptail (available independently on Debian systems), which is required to display the DockSTARTer menus. Arch Linux would need some way to install a package that allows the use of whiptail in order to work. As long as a package exists DockSTARTer could be made to install it automatically.

You can visit https://get.dockstarter.com/ and notice the address bar redirects to the main script in this GitHub repository. You may choose to use `git clone https://github.com/GhostWriters/DockSTARTer ~/.docker` and then `sudo bash ~/.docker/main.sh` for your first run. The instructions in the readme do these steps for you in a single command by letting the script install the repo during the download.

### Final thoughts:

I'm not opposed to adding Arch Linux support to DockSTARTer, but there needs to be a few ways to keep it in line with the rest of the project.

**Comment by faurehu** [comment]
As an Arch Linux user, I find this method of installing very unconventional. We would expect to see docker as a dependency ourselves and then start the containers ourselves.

I understand a requirement for this project is to make it as simple as possible to install, but perhaps it'd be easier to write install instructions for those who are aware of docker.

As for the whiptail dependency, perhaps the UI should be web based for improved portability.

**Comment by nemchik** [comment]
Bump
