### ISSUE TITLE
Map host volume through to SABnzbd container

### ISSUE THREAD

**Issue by jfnz** [GhostWriters/DockSTARTer#396]
Just moved from Atomic-Toolkit to DockSTARTer... Working with containers is proving to be a bit of a learning curve.

I've got the SABnzbd container up and running, but why can't it see a drive I have mounted via NFS? I can see the files in the host OS, I've chown/chmod'd the mount to a regular users, but I can't select the download directory within SABnzbd.

Any pointers?

**Comment by nemchik** [comment]
I did see your message on the ATK issue, and I agree documentation here is not as good (because I'm not very good at it).

https://www.linuxserver.io/docs/persisting-data this is a good piece of info about how volumes work in docker. The idea is your downloads are mapped to a certain folder inside the container. You're looking for /downloads

Each container will have whatever volumes are recommended by the maintainer, the common ones are /downloads /movies /tv and sometimes /data. You set where these folders after mapped to in the DockSTARTer menu or .env file in the compose folder.

I very much do need to improve documentation around here, and your feedback on that is appreciated. Feel free to ask any other questions, or join our discord (chat badge in the readme) for more support.

**Comment by jhakala1963** [comment]
I am a noob to dockers so I thought I would relay how I got a network share to show up on docker containers. It might be obvious to others but not to me at the time. I have a computer I use as a media and file server running ubuntu 16.04 headless server. I have samba installed along with plex on the file server so my windows machines can have access to a 4tb and an 8tb drive I have attached. The docker computer is windows 10 with oracle virtual machine running ubuntu 18.0x with gnome gui. The reason for the gui is for a vpn.   On the ubuntu 18.0x host you make sure you have cifs-utils installed on it.
The files server should have a static ip address which can be done through the router. On the ubuntu 18.0x machine I put in this code in the /etc/fstab  //fileserveripaddress/nameofshare /home/yourloginname/downloads/movies cifs uid=1000,gid=1000,credentials=/home/yourloginname/.credentials,rw,vers1.0
The .credentials file is one made by you with two lines username=yourloginnameoffileserver  password=passwordoffileserver
Once you save it, you can sudo mount -a then restart the whole machine.
your files will show up in docker under /downloads/movies.
You might have to make sure you have that directory in docker first to point to. Make sure there is a space in the fsab file between your fileserver address and the destination address. Make sure you have a period in front of the credentials file you make. I have 3 files in fstab pointing to 3 separate media folders so the different containers have their own directory to play with.
