### ISSUE TITLE
JDownloader2 container

### ISSUE THREAD

**Issue by trohnjavolta** [GhostWriters/DockSTARTer#410]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
JDownloader is a open source download manager written in java. It's especially nice for use with one click hosters.
I'm successfully using this multiarch container maintained by jaymoulin: https://store.docker.com/community/images/jaymoulin/jdownloader

**Comment by juligreen** [comment]
I like the idea, but I'm not certain that this makes sense in the context of this project.
For what are you using JDownloader?
Does it integrate into other services on this project?

**Comment by trohnjavolta** [comment]
I'm using it as a downloadmanager, like nzbget or transmission, deluge etc.
How 

> Does it integrate into other services on this project?

No but neither do other apps supported in dockstarter

**Comment by trohnjavolta** [comment]
> I wanted this as well, So have built it...
> 
> Will be added once this PR is merged - #448

Great but can you explain why you use jlesage/jdownloader-2 docker container and not jaymoulin/jdownloader multiarch container?
I'm fairly new to docker, jaymoulin/jdownloader works good for me on armhf.
Does jlesage/jdownloader-2 even work on arm architecture? I can't find any hints in the dockerfile that it does. + I'm confused about the used java runtime environement. It says openjre but because archive extractor doesn't work it uses oracle jre...Well, does it use both or what?
I just can speak for armhf platform, I read multiple times that oracle jre works better on it with jdownloader 2.

I'm certain you have way more knowledge of all this than I do. Would be great if you could explain your container choice.

**Comment by karl0ss** [comment]
I will have a look into if this image works on arm, I will try deploy it to my raspberry pi tonight, the main reason I prefer this is it exposes the JD GUI via port 5800 so you don't have to use the daemon via cli or use the webui all the time (though you can).

Archive extracting for me works in this container..

Let me see if it will deploy to arm later and I will update this post..

**Comment by trohnjavolta** [comment]
> I will have a look into if this image works on arm, I will try deploy it to my raspberry pi tonight, the main reason I prefer this is it exposes the JD GUI via port 5800 so you don't have to use the daemon via cli or use the webui all the time (though you can).
> 
> Archive extracting for me works in this container..
> 
> Let me see if it will deploy to arm later and I will update this post..

Ok, so there's a "full blown gui" running in the container? I'd prefer a headless instance since I guess it uses up less ressources and the myjd webui works great. But yeah, that's just my 2 cents.
Thx for trying it on arm, if the jaymoulin/jdownloader container is out of question for you, I'll also try the jlesage/jdownloader-2 container on my arm board.
Afaik there are different arm versions and I think they are downwards compatible.
Which raspberry pi do you have? My odroid hc2 is armv7h/armhf.
Rpi2 is armv6 I think and rpi2 armv8 64bit.

**Comment by nemchik** [comment]
I'm removing this from the January milestone and I'm going to close the PRs for the two different versions of this app (they have become a bit stale and I've added/changed things that affect them).

I'm still open to pretty much any app being added to DS, but this particular app seems to have some fragmentation between v1 and v2 still being actively developed and there being a pretty wide selection of docker images between the two versions (some that are multiarch and some that are not) and there not being one primary source that this project could use as the primary image.

**Comment by nemchik** [comment]
Commenting to keep this open.

**Comment by nemchik** [comment]
Just a bit of an update, I continued looking into this and made an updated branch from @karl0ss v2 branch (just getting it in line with more current stuff from recent changes in DS). I re-read what I could find explaining the the status of v1 and v2 and it still seems like there is significant fragmentation between the two. For example https://hub.docker.com/r/jlesage/jdownloader-2/tags hasn't been updated in 7 months as of writing however https://hub.docker.com/r/jaymoulin/jdownloader/tags seems to have more recent releases. I don't see anything specifically making me thing that either of these use the version numbers from the actual jdownloader app itself (either v1 or v2) and the container devs might just be making up their own version numbers and updating when they feel like it.

Since this app is so fragmented and inconsistent I am going to close this issue and advise that anyone looking to run this app do so using overrides. Sorry to keep everyone waiting, I had hoped to find a better solution for this app.
