### ISSUE TITLE
Failed to install latest docker

### ISSUE THREAD

**Issue by karl0ss** [GhostWriters/DockSTARTer#459]
**Describe the bug**
There appears to be an update to docker today, and the script is trying to update when any changes are made, but it is failing to do so

**To Reproduce**
Run the sudo ds command and process through to "create all containers" and select yes
Running Ubuntu 18.04.1 LTS and 16.04.5 LTS

**Expected behavior**
Latest docker should be installed

**Screenshots**
```
+ install_docker
+ local AVAILABLE_DOCKER
++ grep -Po '"tag_name": "[Vv]?\K.*?(?=")'
++ curl -H '' -s https://api.github.com/repos/docker/docker-ce/releases/latest
+ AVAILABLE_DOCKER=18.09.1
+ local INSTALLED_DOCKER
++ sed -E 's/.* version ([^,]*)(, build .*)?/\1/'
++ docker --version
+ INSTALLED_DOCKER=18.09.0
+ local FORCE
+ FORCE=
+ [[ 18.09.1 != \1\8\.\0\9\.\0 ]]
+ info 'Installing latest docker. Please be patient, this will take a while.'
+ tee -a /tmp/dockstarter.log
++ date '+%F %T'
+ echo -e '\e[0m2019-01-10 10:17:20 \e[34m[INFO]\e[0m       Installing latest docker. Please be patient, this will take a while.\e[0m'
2019-01-10 10:17:20 [INFO]       Installing latest docker. Please be patient, this will take a while.
+ curl -fsSL get.docker.com
+ sh
+ fatal 'Failed to install Docker.'
+ tee -a /tmp/dockstarter.log
++ date '+%F %T'
+ echo -e '\e[0m2019-01-10 10:18:05 \e[31m[FATAL]\e[0m      Failed to install Docker.\e[0m'
2019-01-10 10:18:05 [FATAL]      Failed to install Docker.
+ exit 1
+ cleanup
+ [[ /home/karl/.docker == \/\h\o\m\e\/\k\a\r\l\/\.\d\o\c\k\e\r ]]
+ chmod +x /home/karl/.docker/main.sh
+ [[ '' == true ]]
```

Have tried on two systems, using your master and my personal branch.

**Comment by karl0ss** [comment]
Was able to update using the "sudo ds -i" command.

**Comment by nemchik** [comment]
I'm not sure what docker did with this `18.09.1` update but I also had issues with it. I confirmed the issue persisted when using their official installer script directly. DockSTARTer uses their official installer script but I wanted to make sure the issue wasn't something caused by DockSTARTer.

There is not really much I can do to fix this other than provide instructions for how to get it fixed.

```bash
sudo systemctl stop docker
sudo systemctl disable docker
sudo apt-get remove docker-ce
sudo ds -i
sudo ds -c up
```

That should stop and remove docker from your system and then reinstall it and bring your containers back up with their previous configurations.
