### ISSUE TITLE
Guacamole default password?

### ISSUE THREAD

**Issue by Tharic99** [GhostWriters/DockSTARTer#496]
**Describe the bug**
Guacamole container installed from DS and when attempting to access the web url for the first time on port 8080, it asks for an Apache Guacamole username and password. Per the documentation I could find online, the default username would be "guacadmin" and "guacadmin" for the password, but this does not work.

**To Reproduce**
Install guacamole container and attempt to login.

**Expected behavior**
Default "guacadmin" and "guacadmin" username/password combo will work.

**System (please complete the following information):**

Ubuntu 18.04 running under docker

**Additional context**
Also, I created a Let's Encrypt subfolder script for Guacamole as I did not see one in the proxy-confs folder for Let's Encrypt/Nginx.  I'm able to access it remotely via port mapping through Nginx but still cannot login without the correct username/password combo.

**Comment by nemchik** [comment]
For letsencrypt please check out the readme https://github.com/linuxserver/docker-letsencrypt you need to get your cert to generate before the proxy-confs folder will be created.

https://github.com/oznu/docker-guacamole this is the readme for the guac image we use, and you are correct it does seem to indicate `guacadmin` as the username and password. I'll try enabling it myself and seeing what I end up with and report back shortly.

**Comment by nemchik** [comment]
I've enabled guac and I don't see any reason why the default password from oznu's documentation (also in the official apache documentation) wouldn't work. I see you've opened an issue on that repo as well https://github.com/oznu/docker-guacamole/issues/24 maybe oznu will have some insight.

**Comment by Tharic99** [comment]
Sounds good. I got the cert generating fine, my https all works with the proxy-confs just fine, I just noticed that there isn't a sample one for guac, so it may be more of a letsencrypt issue than a DockStarter issue really. I don't know if you have any control over those sample config files get that get dropped in.

**Comment by nemchik** [comment]
I contribute to the repo where the samples are maintained and in fact made many of them, but I do not directly control it. I have a guac sample for subdomain but never finished one for subfolder:

```nginx
# make sure that your dns has a cname set for guacamole and that your guacamole container is not using a base url

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name guacamole.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_guacamole guacamole;
        proxy_pass http://$upstream_guacamole:8080;
    }
}
```

**Comment by Tharic99** [comment]
I'll use that and migrate over to a subdomain. This is what I used for the guacamole.subfolder.conf file

`
# guacamole does not require a base url setting

location /guacamole {
    return 301 $scheme://$host/guacamole/;
}
location ^~ /guacamole/ {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /login;

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_guacamole guacamole;
    rewrite /guacamole(.*) $1 break;
    proxy_pass http://$upstream_guacamole:8080;
}
`

**Comment by Tharic99** [comment]
@nemchik So I noticed last night when adding an app via the DS command that the chown permissions were overwritten again by DockSTARTer. 

I was receiving this error in my Guac logs:

LOG:  could not open temporary statistics file "pg_stat_tmp/global.tmp": Permission denied

Running the

```
sudo chown -R $USER:$GROUP /home/$USER/.docker/config/guacamole/
docker restart guacamole
```

Resolved the issue, but the DS process broke the perms again when DS is run.

**Comment by nemchik** [comment]
The `scriptpath` folder is usually `~/.docker` and will contain the `config` folder by default. Permissions would be set on the `config` folder any time they are set on the `scriptpath` folder unless you choose to move the `config` folder outside of the `scriptpath` folder. A good example would be to set the `config` folder to `~/.config/docker`. This would be done in the `.env` file under the Universal variables.

Here is a list of all events that would cause DS to reset permissions of the `scriptpath` or `config` folder:

- `scriptpath` permissions are set on first time install
- `scriptpath` permissions are set when `ds -i` is run or when the install dependencies menu option is selected
- `scriptpath` permissions are set when `ds -c` is run or when the GUI option to run compose is selected (at the end of configuration menus)
- `scriptpath` permissions are set when `ds -u` is run or when the update DS menu option is selected
- `config` permissions are set when `ds -u` is run or when the update DS menu option is selected
- Permissions are optionally set on any folder entered into the menus when prompted via the GUI

The container in question also sets permissions on specific folders inside its config folder when it starts, which would undo permission changes made by DS.

The conflict would come for example when you choose to enable a new app and run compose to run the new app and permissions are set on the config directory without causing this specific container to start or restart (ex: it was already running and did not have an update available).

The best solution would be for the container to allow us to specify a UID and GID to be used for ownership of the files in its `/config` folder.

A potential alternative would be for you to elect to move your config folder as described above and be mindful that any time you update DS using `ds -u` that you would need to restart the guac container in order to resolve the permissions issue.

Aside from that there is not a lot I can do other than not setting permissions but that has proven to be necessary with a few other containers that do not do well to manage permissions on their own.
