### ISSUE TITLE
Recommended way to add extra folders

### ISSUE THREAD

**Issue by ismay** [GhostWriters/DockSTARTer#522]
By default dockstarter maps music, tv and movies folders for containers that need it. But I want to map extra folders from the host to my plex container (for extra movie, tv, and music sources). What is the recommended way of doing this with dockstarter? Is there an .env file where I can add the extra mappings?

**Comment by nemchik** [comment]
There are a number of ways you can do this actually, and it's entirely up to you because there's no wrong way. Here are some examples:

Assuming you set DS variable `MEDIADIR_MOVIES` to `/mnt/medialibrary/movies` you could mount your disks on your host system inside that folder and have `/mnt/medialibrary/movies/disk1` and `/mnt/medialibrary/movies/disk2` and then Plex and other apps would see `/movies/disk1` and `/movies/disk2`

Another option would be to use `MEDIADIR_MOVIES` for just one disk as you might normally expect to and then use an override (documented in our wiki here https://github.com/GhostWriters/DockSTARTer/wiki/Overrides ) to add whatever other folder you like as a volume. Specifying volumes in this way will add them to the existing volumed defined by DS (not replace the oned DS defines). You can choose to use custom variables that you define in your .env file or you can hard code the volume paths into the compose override file like so:
```yaml
- /path/on/host:/path/in/container
# example
- /mnt/disk2/movies:/movies_4k
```

If you have any other questions feel free to ask. I will close this issue but you may reply to add more comments.
