### ISSUE TITLE
Skip extra bits like ownership and permissions when running docker compose

### ISSUE THREAD

**Issue by kiwijunglist** [GhostWriters/DockSTARTer#562]
**Is your feature request related to a problem? Please describe.**
Taking ownership / permissions is quite slow.

**Describe the solution you'd like**
Skip this bit when running `sudo ds -c up`

**Describe alternatives you've considered**
I'd like to have an option called `sudo ds -c -skip up`

This will just merge the .env and the docker override yaml then run the docker compose and do nothing else.

**Comment by nemchik** [comment]
Adding a note here as well since I referenced this in #567 

The skip flag may require some significant reworking of how DS handles cmdline (which was discussed here #384 and scrapped for the moment but we can reopen if required). I will reassess how to handle this and determine if the rework is required or if there is an easier way to accomplish this goal.

**Comment by nemchik** [comment]
Adding a reference to #577 

Once that merges I will reconsider how to approach this. The above references are still valid and should be considered alongside this when making the changes needed for this.

**Comment by nemchik** [comment]
#606 should solve this, but not by actually adding the ability to skip setting permissions. Instead we're just not setting permissions at all on the contents of config directory anymore. Feel free to test (instructions in the comments of the PR).
