### ISSUE TITLE
bug: symlink for ds wrong when path does not start with /

### ISSUE THREAD

**Issue by phenonymous** [GhostWriters/DockSTARTer#599]
### The issue:
If you invoke main.sh by relative path it does not symlink ds to the correct path

### Reproduction:
Example of invocations that does not work
assuming the current working directory is /home/${USER} and repo cloned to /home/${USER}/dockstarter

- `$ sudo bash dockstarter/main.sh -i` 
- `$ chmod +x dockstarter/main.sh && sudo dockstarter/main.sh -i` 

Note here that this is also true for any location that is relative

However the follow Do work as long as globbing is allow, which is assumed here
- `$ sudo bash ./dockstarter/main.sh -i`

that is because . is the absolute path of the current directory

### Expectated behaviour
Symlink for ds should always be the absolute path

I will make a PR for this

**Comment by nemchik** [comment]
I actually think this is related to a bug I found recently that caused me to put a hack-y workaround in DS for Travis to pass builds.

I believe the issue is with this function https://github.com/GhostWriters/DockSTARTer/blob/master/main.sh#L53-L67 `get_scriptname` (you can see my Travis hack in there) but I haven't dug in deep enough to confirm or fix it.

A PR is welcome!
