### ISSUE TITLE
enhancement: allow script location to be other than ${DETECTED_HOMEDIR}/.docker

### ISSUE THREAD

**Issue by phenonymous** [GhostWriters/DockSTARTer#602]
The current implementation of main does not allow DockSTARTer to be any other location than 
${DETECTED_HOMEDIR}/.docker

The issue lies in https://github.com/GhostWriters/DockSTARTer/blob/1fd12e999080093f45a35bedfb78ce0f2c7c3299/main.sh#L165-L179 which always checks if the repository is at ${DETECTED_HOMEDIR}/.docker if main is run with no arguments. Which in turn clones the repo and run the install script even if the install script was run previously from another location.

Solution is to add another check if the install script was previously run. This can be done by matching the ds symlinked location to the script location. This allows the use of both `sudo ds` and  `sudo bash <path here>/main.sh`

This is not an issue for the general user but it's nice if the DockSTARTer location is not hardcoded.

I can make a commit with a suggested solution which you can check and then I'll make a PR for it

**Comment by nemchik** [comment]
Initially I didn't want to hardcode the location but over time I ended up doing it because I didn't know a decent way to check where it would have been previously installed. One of the reasons I did it this way was to accommodate the installation instructions in the readme (the basic ones, not the advanced ones - which I know are considered bad practice but that's why I include the advanced instructions). When that bash curl stuff from the readme is run DS only has access to anything in `main.sh` until it can confirm if it's already been installed somewhere on the system and then relaunch itself from that location. Checking the symlink location is a great idea but one thing we absolutely do not want is to allow DS to be run by the root user or from any location inside `/root/` which I already have some checks in place for, but we'll need to ensure that any changes we do to allow DS to run from another location don't break out of those limitations. I'm not opposed to DS maybe existing in `/opt/` or something like that, but I haven't researched enough to decide the best way to handle that. Aside from the possibility of `/opt/` I've generally held to the belief that DS should exist somewhere inside a user directory such as `/home/something/` but only because DS is designed to be run as a user (with sudo rights) and NOT as root. I have some work to do on handling permissions a well, but that's a different topic. Lastly we of course need to make sure that any user updating their DS won't be negatively affected by the script trying to relocate itself for example (which I don't think is what you're after with this, but I'm just throwing the comment out there so that it's clear).

Anyway I'd love to see a commit and we can discuss it and determine the best way to improve this because I do agree it isn't a good practice to hard code the location like we are.

**Comment by phenonymous** [comment]
A check for DS being in a safe path is absolutely neccessary and that is something I did not think of when I posted this.

I have several solutions but I'm not sure what the best approach is. So I have narrowed it down to 3 use cases

1. Users who just want to get up and running with minimal configuration - this use case is the current one as the advanced install is broken
2. Users who intend to have a dedicated DS user or for other pruposes do not want DS in /home

The 3rd case, which is my case, are users who understands the risk and want full control. I will not implement this because of the reasons you stated. Besides users in this group probaly already know some bash and can modify the script to their liking but that is another topic.

**Comment by nemchik** [comment]
In your number 1 you mention the advanced install is broken. I just tried the advanced instructions from the readme and it seemed fine. Can you elaborate?

Number 2 I would consider two different items:

- Users who want a dedicated user for DS: Need to understand that MOST of the containers in DS are designed to need certain permissions and/or file ownership on the files accessed outside of the containers that get mounted using volumes. Because of this it's recommended to run as the primary user on the system. Having a separate DS user would mean any file touched by most of the containers would end up being owned by that DS user. That being said I'm not sure why someone would want to have all their files owned by a separate user rather than their primary user, but I'm not going to say it's not a possibility.
- Users who don't want DS in `/home`: I'm willing to entertain this as I think it would be beneficial for DS to be able to exist in a place like `/opt`. My main reasoning for that rationale is actually the symlink. When a user runs DS it creates a system wide symlink to their user folder. Other users on the system may not be able to run the `ds` command because the symlink would be pointing to `main.sh` inside of a different user's home directory. Again this goes a bit pack to the above point about permissions since it wouldn't matter which user runs DS if only one user can be designated as the one the containers run as.

Both of the above involve accounting for systems where there are multiple user accounts, which DS currently just isn't built for, and I'm not convinced that there are true long term benefits to doing it because of how the containers run as a specific user.

The 3rd case you mention is absolutely one that I wouldn't mind addressing because I don't want DS to feel like it's forcing things on people that really aren't necessary and to be honest the name of the folder that DS runs from is trivial at best. I really don't care what the folder is named. Being able to have it run from another folder isn't a bad idea, it's just a matter of ensuring it doesn't exist in places we know it shouldn't and that we can detect where it is (using the `readlink` seems to be a good idea for that).

**Comment by phenonymous** [comment]
> In your number 1 you mention the advanced install is broken. I just tried the advanced instructions from the readme and it seemed fine. Can you elaborate?

Sure, and this is why I raised this issue. The installation is not the problem per se but if you use any location other than `${DETECTED_HOMEDIR}/.docker` it clones the repo to that location and runs the install script again and effectively overrides the previous install.

Say you clone this repo to `${DETECTED_HOMEDIR}/ds` and run `$ sudo bash ${DETECTED_HOMEDIR}/ds/main.sh -i` - `ds` now points to `${DETECTED_HOMEDIR}/ds/main.sh` which is correct, but if you run `$ sudo ds` this part kicks in
https://github.com/GhostWriters/DockSTARTer/blob/2407ca0e5033509b34a8bf457519a74cf69c0665/main.sh#L163-L168

**Comment by nemchik** [comment]
I see, so it's not that the advanced install is broken, it's just that DS insists it must exist in one specific place and that's not where you want it 😄 

I think if we setup some code that reads the location of the DS symlink and if it doesn't exist then check the location of the script itself to ensure it's only somewhere in /home/something or /opt and then sets that value of where it is into a variable then we could replace all use of `${DETECTED_HOMEDIR}/.docker` with that variable.

The other thing I just realized i need to explain a little better is the basic install instructions in the readme will curl a copy of the main.sh file into a random location that will not be in /home or /opt so the first time setup needs to account for that and clone the repo somewhere for the user.

**Comment by phenonymous** [comment]
I have a commit ready, just testing some stuff before I push

**Comment by phenonymous** [comment]
This is a good start and it is production ready but I'm sure you have some feedback.

This does not break the main install procedure. It only shows and takes a different route if it detects that the script is run from a cloned repo that is not in ${DETECTED_HOMEDIR}/.docker 

It still does the root check for custom install and in addition checks that DS is not in the /root folder. Other protected folders can easily be added

**Comment by nemchik** [comment]
I've added some comments.

I'm still not opposed to the idea of finding a way to not force the `~/.docker` location. Also I don't know if the term "advanced install" is really what this should be called. it's more "custom install location".

**Comment by nemchik** [comment]
Also i've been working hard on #606 which may affect these changes a bit (just a heads up).

**Comment by phenonymous** [comment]
I have also been working hard on this issue. I took your feedback and improved it alot. It now handles any location and throws an error if you try to run it under any of the default invalid locations, which you can change. 

It also moves the directory to `${DETECTED_HOMEDIR}/.docker` if you answer that you do not want a custom location if you happen to have the folder in another location.

**Comment by nemchik** [comment]
I'll have a look in a little bit :smile:

**Comment by phenonymous** [comment]
So I think I've come up with an elegant solution that uses the symlink to determine the current installation environment. I hade to move `run_script 'symlink_ds'` around to make it work.

https://github.com/phenonymous/DockSTARTer/commit/ce3b08a7bd8f27c3b6e92f2715c75aed1f441b88

Take a look. I have not tested this yet but you should get the general idea
