### ISSUE TITLE
Tautulli cant see the Plex server

### ISSUE THREAD

**Issue by artiedarrell** [GhostWriters/DockSTARTer#619]
**Describe the bug**
Plex is running per Portainer, but Tautulli cannot seem to see the server

![image](https://user-images.githubusercontent.com/17505190/55268858-8900fe00-526c-11e9-9828-cd7dec32c2d3.png)

Ubuntu 18.04
New installation

**Comment by artiedarrell** [comment]
![image](https://user-images.githubusercontent.com/17505190/55268882-c6658b80-526c-11e9-9055-a7b73f388be4.png)

**Comment by nemchik** [comment]
In the first screenshot change `localhost` to `plex`

Docker containers talk to each other by name.

**Comment by artiedarrell** [comment]
Ah, cheers


Was that in the documentation somewhere? Im sure I'll have similar
questions in the future.

**Comment by nemchik** [comment]
I don't believe we have it documented anywhere, but that's standard Docker behavior. It wouldn't hurt for it to be in our wiki.

**Comment by artiedarrell** [comment]
changing "localhost" to "plex" doesnt work either (sorry brand new to docker...)

I also tried "localhost/plex", "localhost/plexinc" as well as the containerid. 

`docker ps -a `

returns

![image](https://user-images.githubusercontent.com/17505190/55276587-4246ee80-52d4-11e9-8052-1b17c5d8a00f.png)

![image](https://user-images.githubusercontent.com/17505190/55276603-5f7bbd00-52d4-11e9-9965-9429abb9d458.png)

**Comment by nemchik** [comment]
Run `docker exec tautulli ping plex -c4`

This tells Tautulli to check that it can see Plex. If you don't see it find an IP address then something isn't working right.

BTW, just to confirm you're running both Plex and Tautulli in Docker containers setup by DockSTARTer?

**Comment by artiedarrell** [comment]
ping looks to be working well

user@server:~$ docker exec tautulli ping plex -c4
PING plex (172.18.0.14): 56 data bytes
64 bytes from 172.18.0.14: seq=0 ttl=64 time=0.076 ms
64 bytes from 172.18.0.14: seq=1 ttl=64 time=0.109 ms
64 bytes from 172.18.0.14: seq=2 ttl=64 time=0.118 ms
64 bytes from 172.18.0.14: seq=3 ttl=64 time=0.079 ms

yes both were installed by DockSTARTer 

new Ubuntu 18.04 install in VirtualBox

Nothing else installed except what was installed by DockSTARTer 

UFW is off

**Comment by nemchik** [comment]
Everything checks out, it should work the way you have it in your most recent screenshot. UFW wouldn't affect this BTW.

You already have Plex working and can login to it and watch media?

**Comment by artiedarrell** [comment]
ok solved it...

when editing inside portainer, it appears that none of the changes are actually saved unless you click deploy the container...

![image](https://user-images.githubusercontent.com/17505190/55277873-90afb980-52e3-11e9-84b2-96947961923d.png)


so plugged in the claim token and changed the ADVERTISED_IP to "http://localhost:32400/", which was originally, for some reason, set to 192.168.x.x (yes, x.x was in the field) and then hit "deploy the container"

half of this is probably my not knowing docker at all haha

![image](https://user-images.githubusercontent.com/17505190/55277856-6a8a1980-52e3-11e9-8180-61c80e4d2ca6.png)

**Comment by nemchik** [comment]
The things you edited in portainer are all settings and variables in DS. I recommend you run `ds` and select config > full. From there go through the options for Plex and others and set them how you need. You'll be shown the current values and given the option to keep or change them (you need to change them). The reason you want to do this in DS instead of portainer is that changed made in portainer are somewhat temporary. For example if you stop and remove the Plex container your portainer changes will be lost. There settings and variables in DS will be persistent even when removing and recreating containers. Also if you use DS to add another container it will overwrite the changes you've made to Plex because everything created by DS is part of a designated stack.

Lastly `ADVERTISED_IP` is set by default to `http://192.168.x.x:32400/` in DS in hopes that it's obvious you need to change it, however `http://localhost:32400/` is not the correct value to serve it's intended purpose. You want it set to the IP address of your system.

Portainer is a great tool for learning how things work, but DS sets up compose for you which is much more powerful and deliberate.
