### ISSUE TITLE
Location blocking

### ISSUE THREAD

**Issue by nemchik** [GhostWriters/DockSTARTer#655]
Follow up from #646

Should we block DS from running from certain locations?

Should we only block DS from cloning itself into certain locations? (Referring to the clone it does on first run - users could relocate the install without limitations after the initial clone)

**Comment by phenonymous** [comment]
I do not think DS should be blocked from running from certain locations. If it is in "location A" then the user probably had the right permissions to clone/move it there. That is something DS can't control and should not force because it really isn't DS's responsibility. 
On linux/osx there already are some paths a user can't put files or create directories in, not even as root. So the most critical paths already has some restrictions.

However, there should be some safety checks in setting permissions because that is nothing the user can control. Putting DS directly in e.g. `/etc` so you would run DS from `/etc/main.sh` and then have the script taking ownership of the entire `/etc` path is really bad, altough I do not think that's possible but you get the gist.

**Comment by nemchik** [comment]
I think you're right on all of this, and DS already has restrictions in place to prevent settings permissions on system folders for various reasons. Cloning into a system folder without using a subfolder would not need to be prevented (if a user is so determined) but DS won't set any permissions in those cases.
