### ISSUE TITLE
Fedora 30 - Permission Denied

### ISSUE THREAD

**Issue by UnR34L** [GhostWriters/DockSTARTer#678]
Testing all the software I use before I make the move to Fedora 30.
As of right now the docker repo hasn't been updated for 30 (https://github.com/docker/for-linux/issues/600) but I thought I would get started now and look for problems.

After manually installing the latest docker, ds will run once then spit out errors after that. If I remove /tmp/dockstarter.log it will work.

![image](https://user-images.githubusercontent.com/5008396/57227468-600d1f00-7009-11e9-873c-cb0efab0df75.png)

**Comment by nemchik** [comment]
Just a note for myself, maybe we need sudo with all the tee commands.

**Comment by anotb** [comment]
Same issue on Arch. 

```
sudo ds
tee: /tmp/dockstarter.log: Permission denied
2019-06-14 16:33:40 [INFO]       Setting permissions for /home/user/.docker/main.sh
tee: /tmp/dockstarter.log: Permission denied
2019-06-14 16:33:40 [ERROR]      DockSTARTer did not finish running successfully.
```

```
sudo rm /tmp/dockstarter.log && ds
2019-06-14 16:27:46 [INFO]       Setting permissions for /home/user/.docker/main.sh
2019-06-14 16:27:46 [INFO]       Taking ownership of /home/user/.docker/main.sh for user 1000 and group 1000
2019-06-14 16:27:46 [INFO]       Setting file and folder permissions in /home/user/.docker/main.sh
2019-06-14 16:27:46 [ERROR]      Invalid Option

```

**Comment by nemchik** [comment]
FYI I've updated our readme to include links to information about systems supported by `docker-ce`

https://docs.docker.com/install/linux/docker-ce/fedora/#os-requirements
You'll note that Fedora 30 is not yet listed. The `docker-ce` repositories do not include stable release packages for Fedora 30 yet.
https://download.docker.com/linux/fedora/30/x86_64/
This is what we have for Fedora 29:
https://download.docker.com/linux/fedora/29/x86_64/stable/Packages/

I have tested Fedora 29 and there are no issues with it. The issue you described sounds more like an issue with permissions (you need to login as a non-root user with sudo permissions).

I would recommend running `ds -u` and if the problem continues let me know, but again Fedora 30 isn't supported by `docker-ce` so there may be more issues and I recommend using Fedora 29, or one of the other systems listed as supported in our readme.

**Comment by UnR34L** [comment]
But did you test on Arch?

**Comment by nemchik** [comment]
Arch is not listed as a supported platform on https://docs.docker.com/install/#supported-platforms and as such will not be officially supported by this project. I do believe that some recent changes to DS may make it possible to run on Arch, but you will be responsible for installing all packages and dependencies in order to keep DS from attempting to do so. Arch uses the `pacman` package manager that we have not accommodated in the scripts. Only `apt`, `dnf`, and `yum` are accounted for since they are the default package managers of the supported platforms on Docker's official documentation.

I am not opposed to discussing the possibility of including support for Arch in the future if you'd like to join our Discord and chat about it, but it is not a priority at the moment (I have some other things moving forward).

**Comment by UnR34L** [comment]
Ok, I was just wondering, I'll create a new issue when/if docker-ce supports F30.

But from what I've read, Fedora will be moving to moby-engine.

**Comment by nemchik** [comment]
It'll be up to docker themselves to add support. Not really Fedora. I'm sure they will, just a matter of when.
