### ISSUE TITLE
UniFi-Video

### ISSUE THREAD

**Issue by jlounsbery** [GhostWriters/DockSTARTer#737]
Since the UniFi Controller and UNMS have been added, would anyone be willing to integrate UniFi Video for the full Ubiquiti product line?

**Comment by nemchik** [comment]
https://github.com/GhostWriters/DockSTARTer/pull/639 UNMS actually never made the cut due to no one responding for testing. If you're able/willing to test I can update the branch with the most recent changes and let you know when it's ready.

As for UniFi Video, I'm fine adding it if we have a decent image to use for the container and someone can test to confirm it works.
