### ISSUE TITLE
Plex Multiple Volumes

### ISSUE THREAD

**Issue by mouzzampk2014** [GhostWriters/DockSTARTer#746]
Hi, currently compose file contains and plex look shows duplicate movies, tv and music folders contains same data. Is it possible to only keep one such volume for each label. Thank you

```    - ${MEDIADIR_MOVIES}:/data/movies
    - ${MEDIADIR_MOVIES}:/movies
    - ${MEDIADIR_MUSIC}:/data/music
    - ${MEDIADIR_MUSIC}:/music
    - ${MEDIADIR_TV}:/data/tv
    - ${MEDIADIR_TV}:/tv

**Comment by mouzzampk2014** [comment]
![1](https://user-images.githubusercontent.com/44548525/60375819-176b5400-9a03-11e9-9192-24ec9a5cc821.jpg)

**Comment by nemchik** [comment]
This is actually intentional.

https://hub.docker.com/r/linuxserver/plex/ recommends using `/data/tv` while other apps simply want `/tv`. DS includes both so that every app needing TV gets `/tv` but also gets whatever the dev recommends for the container.

This is also why the VPN containers have `/data` and `/downloads` mapped to the same location. 

Something to keep in mind about docker images is they can specify volumes like you see here https://github.com/binhex/arch-rtorrentvpn/blob/master/Dockerfile for `/data`. If you don't include those volumes when you credit a container from the image then docker will make a fake volume in a system folder on your rootfs and take up space on your hard drive that you'll have to purge later. So we can't leave them out.

I'm the case of Plex they don't define the volumes in their Dockerfile, but they have it in their documentation. For the sake of not deviating from their recommendations (so that users can get support from the devs) we include what they specify.

**Comment by mouzzampk2014** [comment]
Cool that's perfectly make sense. But there is no way we can purge `/data` volume using `override`?

**Comment by nemchik** [comment]
Unfortunately no. You can add things, or replace things, but not take away. Best thing to do is ignore them. They only exist inside certain containers.
