### ISSUE TITLE
Naming Convention Issue: codeserver vs code-server

### ISSUE THREAD

**Issue by si1k** [GhostWriters/DockSTARTer#831]
**Describe the bug**
DockStarter creates the VS Code container named codeserver whereas linuxserver.io names the container code-server. This creates issues with the linuxserver.io "ecosystem" such as integration and reverse proxy templates that refer to the container as code-server. 

This seems like an easy fix and I am happy to fix and do a PR. However, additional logic for previous users should probably be added to run `docker rename codeserver code-server` if the previously installed container exists. I am unsure of the best place to insert this command within dockstarter.

**To Reproduce**
Review yml for codeserver and notice the container is created as codeserver, then review the linuxserver.io built container named code-server.

**Expected behavior**
The naming convention should be the same. 

**System**
Universal issue. 

**Additional context**
I believe this is a larger issue than what it appears as new users will struggle with noticing the missing "-" in the container name and impacts the letsencrypt/nginx/proxy-conf.

**Comment by nemchik** [comment]
The reason for the naming convention in DS is we use app names in bash variables in your `~/.docker/compose/.env` file and bash variables do not allow the dash character. Specifically for example you can see `CODESERVER_NETWORK_MODE` in your `.env` file. We could not make that variable `CODE-SERVER_NETWORK_MODE` due to bash not allowing the dash character. The variable naming and container naming is used across DS in various ways such that the name of the container needs to match the name of the variables used. nginx variables also cannot use dashes which is why you see the underscores used in the variable names even in LSIO's proxies in these scenarios: https://github.com/linuxserver/reverse-proxy-confs/blob/e2f4bb469effb296235bef0d42dac06f4c703a20/code-server.subdomain.conf.sample#L27

The simplest solution is to simply modify the line above to read: `set $upstream_code_server codeserver;`

I have discussed this with aptalca (the lsio team member who maintains the proxies and letsencrypt repo) in an issue or pull request on their repo some time in the past and it was decided to keep the dashes in container names and in the proxy configs.

It would be possible for me to make adjustments in DS to accomodate for this, but there are so few apps with this specific issue (`code-server` and `tt-rss` being the only two i can recall off the top of my head) that I'm not sure it's worth the effort by comparison to simply instructing users to remove the dash in their proxy config.
