### ISSUE TITLE
Prevent IP's from changing on restarts

### ISSUE THREAD

**Issue by mildfuzz** [GhostWriters/DockSTARTer#852]
**Is your feature request related to a problem? Please describe.**
This would resolve me having to manually update the IP of deluge in Sickchill whenever I notice my shows are not downloading.

**Describe the solution you'd like**
I think a more widely useful feature is an ability to lock down IP's so that they do not change across restarts

**Describe alternatives you've considered**
It might also be possible to simply update the IP's of relevant services, but I fear this would be needed for every use case, where as fixing the IP's will probably have broad application

**Additional context**
Would be keen to have a go at fixing this myself if anyone can give me a few pointers.

**Comment by nemchik** [comment]
This is doable by defining the IP of each container, but also not required.

In Sickchill (or any app DS runs for you) you can allow the app to talk to other apps by hostname rather than IP. Rather than using `172.18.1.15` (or whatever it gets) simply type `deluge` in the box prompting you for hostname/IP.
