### ISSUE TITLE
E: Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by techbytesrn** [GhostWriters/DockSTARTer#926]
**Describe the bug**
unable to get docker to install shown using the line below

**To Reproduce**
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install curl git
bash -c "$(curl -fsSL https://get.docker.com)"

The error shown above is received after the last command shown above is entered and the files are downloaded.

I am installing this on debian buster for raspberry pi.  I have been able to reproduce the error.

- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**System**
(please complete the following information):

- OS: [e.g. Debian]

**Additional context**

**Comment by nemchik** [comment]
Reboot the system and try all those steps again from the top.

**Comment by techbytesrn** [comment]
Eric:

Thanks for the reply.
I tried what you suggested and also created a new sd card.
Still had the error.

I am using Debian Buster. Didn't want to try the new Raspberry Pi branded
OS that just came out. Using a Pi 4b 1gb board and 32gb micro sd card.

Ron

**Comment by nemchik** [comment]
Can you post the log of when this error happens so I can see what's being run before it?

**Comment by techbytesrn** [comment]
Will be happy to do so. I am creating a new cd card now. Do you want a copy
of what going across the screen or from something like /var/log/messages ?

Ron

**Comment by nemchik** [comment]
A copy of what's on the screen would be good. Screenshot of something.

**Comment by techbytesrn** [comment]
ok.  Just wanted to get you the right thing.
I just finished creating a boot sd using the Raspberry Pi branded OS that
just came out
I was able to get past the get.docker.com line without any errors that I
could see

bash -c "$(curl -fsSL https://get.dockstarter.com)" got this one the screen
when the above line was executed

2020-06-07 02:33:01 [WARN  ]   Attempting to clone DockSTARTer repo to
/home/pi/.docker location.
environment: line 436: git: command not found
2020-06-07 02:33:01 [FATAL ]   Failed to clone DockSTARTer repo to
/home/pi/.docker location.
2020-06-07 02:33:01 [ERROR ]   DockSTARTer did not finish running
successfully.

Ron

**Comment by nemchik** [comment]
Can you run `git --version`?

**Comment by techbytesrn** [comment]
Got an error when I tried to get git's version.  Reran the sudo apt-get
install curl git line and it said that curl was installed but git wasnt
installed.
dont recall seeing an error about git not installing.

Just ran the get.dockstarter.com line and it seemed to run without error.
Rebooting now.

Once I get this up and running, will repeat the install process to see if
the same errors shows.
Really appreciate your help on this.
I am going to be doing a video for my youtube channel about this and will
be to mention your help.

Ron

**Comment by nemchik** [comment]
On your subsequent runs if you do have trouble and we're able to narrow it down I can either adjust the script or the install instructions.

**Comment by techbytesrn** [comment]
Eric:

Thanks.  Will be happy to help.
most of my audience doesnt have a lot of docker experience, so I want to
help them see there is an easier way to install docker.

Ron

**Comment by nemchik** [comment]
Ron

I wanted to check in and see if you've had any luck with this?

**Comment by techbytesrn** [comment]
Eric:

Sorry for the delay on my end.  Had to spend a little more time creating
one of the videos for my youtube channel than expected.
Will work on this tonight or tomorrow and get the information to you.

Ron

**Comment by nemchik** [comment]
No problem. Let me know if you need anything.

**Comment by minidarknova** [comment]
Hi there, I get the same error. I do have installed both GIT and CURL, can see their version. But DOCKER CE can't be installed.

**Comment by nemchik** [comment]
Can you visit https://get.docker.com/ and follow the instructions to do the install and post the full output here if it fails?

**Comment by minidarknova** [comment]
pi@rasp:~ $ sudo apt-get install docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree
Reading state information... Done
containerd.io is already the newest version (1.2.13-2).
containerd.io set to manually installed.
docker-ce-cli is already the newest version (5:19.03.11~3-0~raspbian-buster).
docker-ce-cli set to manually installed.
docker-ce is already the newest version (5:19.03.11~3-0~raspbian-buster).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up docker-ce (5:19.03.11~3-0~raspbian-buster) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2020-06-21 00:59:49 BST; 56ms ago
     Docs: https://docs.docker.com
  Process: 12708 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 12708 (code=exited, status=1/FAILURE)
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by minidarknova** [comment]
Not sure if this is what you were looking for.   
I followed the instruction here:   https://docs.docker.com/engine/install/debian/

**Comment by nemchik** [comment]
This is what I meant
```bash
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
```

**Comment by minidarknova** [comment]
pi@rasp:~ $ curl -fsSL https://get.docker.com -o get-docker.sh
pi@rasp:~ $ sh get-docker.sh
# Executing docker install script, commit: 26ff363bcf3b3f5a00498ac43694bf1c7d9ce16c
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sudo -E sh -c curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sudo -E sh -c echo "deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sudo -E sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by nemchik** [comment]
I googled that error

https://phoenixnap.com/kb/fix-sub-process-usr-bin-dpkg-returned-error-code-1

**Comment by minidarknova** [comment]
OK So I managed to fix it. the culprit was the VPN...OpenVPN, I disabled it running in the background using: 

`sudo service openvpn stop`   

Ran the process of installation of docker and it worked.

**Comment by nemchik** [comment]
Great news!

**Comment by angrycuban13** [comment]
Resolved per OP.
